---
- name: Converge
  hosts: all
  become: true
  gather_facts: true

  roles:
    - role: install-packages
      vars:
        input_debug: true
        input_ubuntu_repositories:
          - repo: "deb [arch={{ ansible_architecture }} signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main"
            filename: "hashicorp"
            self_signed_repository_key: https://apt.releases.hashicorp.com/gpg
            keyring_name: hashicorp-archive-keyring.gpg
            state: present
        input_packages_to_install:
          - "nano"
        input_packages_to_remove:
          - "vim-tiny"
      when: ansible_os_family == "Debian"

    - role: install-packages
      vars:
        input_debug: true
        input_packages_to_install:
          - "nano"
        input_packages_to_remove:
          - "vim-tiny"
      when: ansible_os_family == "Alpine"

    - role: install-packages
      vars:
        input_debug: true
        input_redhat_repositories: []
        input_packages_to_install:
          - "epel-release"
          - "nano"
        input_packages_to_remove:
          - "vim-tiny"
      when: ansible_os_family == "RedHat"
